language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install build-essential python-dev python-numpy python-numpy-dev python-scipy libatlas-dev g++ python-matplotlib ipython

install:
  #- pip install -r requirements_test.txt3
  - pip install codecov

script:
  - coverage run --source=FukuML setup.py test

after_success:
  - codecov

notifications:
  email:
    - fukuball@gmail.com