language: python

sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran

before_install:
  - pip install -U pip setuptools wheel

install:
  - travis_wait travis_retry pip install -r requirements_test.txt
  - travis_wait travis_retry pip install codecov
  - travis_retry python setup.py dev

script:
  - coverage run --source=FukuML setup.py test

after_success:
  - codecov

notifications:
  email:
    - fukuball@gmail.com